### ISSUE TITLE
Do more check for price and discount percent

### ISSUE THREAD

**Issue by raozhiming** [elastos/Elastos.ORG.ElaPay#11]
![checkvalue](https://user-images.githubusercontent.com/38715431/40906951-e89825d4-6814-11e8-9c44-e313b8d71f53.png)

<img width="411" alt="ui check2" src="https://user-images.githubusercontent.com/38715431/40903048-a546012c-6808-11e8-95a4-5dcac2ee9857.png">

**Comment by raozhiming** [comment]
if the discount is 100, you cann't checout the order, and do not show the error information

**Comment by hoangnv1203** [comment]
I check with: 
- price do not <= 0
- discount pecent must be 0 <= discount < 100

**Comment by raozhiming** [comment]
discount pecent < 0 is ok

@hoangnv1203

**Comment by hoangnv1203** [comment]
Ok, I fixed
