### ISSUE TITLE
callback api should check response status when sending callback message

### ISSUE THREAD

**Issue by xiaomingfuckeasylife** [elastos/Elastos.ORG.ElaPay#8]
should check response status , only when the status equals to 200 update status to `send` , otherwise resend every 2 minutes , ten times at most , if still not get 200 response status , update status to `invalid` or something like that .

**Comment by SharedMocha** [comment]
Fixed.
2 minute logic should not be at the code level instead we should set background timer to 2 minutes as block gets generated approx 2 min. Change this for production.

This way job runs every 2 minutes and when ever it hits 10 retires it will update the status.
